baseURL = "https://hugosibony.com" # The URL of your site
languageCode = "en-us" # The language you want to display the site in
title = "Hugo Sibony" # The title you want to appear in the address bar
theme = "hugo-developer-portfolio" # The theme, don't change this

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

# navigation
[menu]
  [[menu.main]]
  name = "About"
  URL = "about"
  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  [[menu.main]]
  name = "Contact"
  URL = "contact"


[markup.goldmark.renderer]
    unsafe= true
[markup.highlight]
    style = 'friendly'
[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Portfolio of Hugo Sibony" # The description of your site
author = "Hugo Sibony"


    [params.contact]
    formAction = "https://formspree.io/f/xrgvvkge"

    # This contains the contact information for the footer
    [params.footer]
    email = "hugo@hugosibony.com"
    address = "Paris, France"